QT += core gui opengl

unix:!macx {
        LIBS += -lglut -lGLEW -lGLU
}
win32 {
        LIBS += "C:\Archivos de programa\Microsoft SDKs\Windows\v6.1\Lib\glew32.lib"
}
macx {
        LIBS += -framework GLUT
}

TARGET = Thoth
TEMPLATE = app


SOURCES += main.cpp\
    Objects/objectmanager.cpp \
    Objects/object3DFile.cpp \
    Objects/enviroment.cpp \
    Objects/car.cpp \
    Objects/absObject3D.cpp \
    Scene/scene.cpp \
    Scene/fragmentview.cpp \
    Utils/vector3D.cpp \
    Utils/point3D.cpp \
    Utils/point2D.cpp \
    Cameras/sphericalcamera.cpp \
    Cameras/freecamera.cpp \
    Cameras/fixedcamera.cpp \
    Cameras/cameramanager.cpp \
    Cameras/cameraabs.cpp \
    Lights/lightmanager.cpp \
    Lights/light.cpp \
    Loaders/settingsexporter.cpp \
    Loaders/lightloader.cpp \
    Loaders/fileParser.cpp \
    Loaders/camerasloader.cpp \
    Ui/lightswindowqt.cpp \
    Ui/importsettingsqt.cpp \
    Ui/exportsettingsqt.cpp \
    Ui/errorwindow.cpp \
    Scene/contextgl.cpp \
    Ui/mainwindow.cpp \
    Ui/camerawindowqt.cpp \
    Ui/carswindowqt.cpp \
    Objects/absModels.cpp \
    Loaders/settingsimporter.cpp \
    Commands/camerascmd.cpp

HEADERS  += \
    Objects/objectmanager.h \
    Objects/object3DFile.h \
    Objects/enviroment.h \
    Objects/car.h \
    Objects/absObject3D.h \
    Scene/scene.h \
    Scene/fragmentview.h \
    Utils/vector3D.h \
    Utils/util.h \
    Utils/point3D.h \
    Utils/point2D.h \
    Cameras/sphericalcamera.h \
    Cameras/freecamera.h \
    Cameras/fixedcamera.h \
    Cameras/cameramanager.h \
    Cameras/cameraabs.h \
    Lights/lightmanager.h \
    Lights/light.h \
    Loaders/settingsexporter.h \
    Loaders/lightloader.h \
    Loaders/fileParser.h \
    Loaders/camerasloader.h \
    Ui/lightswindowqt.h \
    Ui/importsettingsqt.h \
    Ui/exportsettingsqt.h \
    Ui/errorwindow.h \
    Scene/contextgl.h \
    Ui/mainwindow.h \
    Ui/camerawindowqt.h \
    Ui/carswindowqt.h \
    Objects/absModels.h \
    Loaders/settingsimporter.h \
    Commands/camerascmd.h

FORMS    += \
    Ui/lightswindowqt.ui \
    Ui/importsettingsqt.ui \
    Ui/exportsettingsqt.ui \
    Ui/errorwindow.ui \
    Ui/mainwindow.ui \
    Ui/camerawindowqt.ui \
    Ui/carswindowqt.ui

OTHER_FILES += \
    simple.vert \
    simple.frag \
    Media/Models/Circuit/ubs_decal_a.dds \
    Media/Models/Circuit/ubs_board_a.dds \
    Media/Models/Circuit/track_diff_a_02_d.dds \
    Media/Models/Circuit/toilet_block_a.dds \
    Media/Models/Circuit/team_specific_monitors_d.dds \
    Media/Models/Circuit/team_specific_garage_high_d.dds \
    Media/Models/Circuit/standee_parcfermeplace_a_01_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpl_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpk_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpj_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpi_d.dds \
    Media/Models/Circuit/sponsorx_cats_varph_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpg_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpf_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpe_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpd_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpc_d.dds \
    Media/Models/Circuit/sponsorx_cats_varpa_d.dds \
    Media/Models/Circuit/sponsorx_cats_varca_d.dds \
    Media/Models/Circuit/sponsorx_cats_varbv_d.dds \
    Media/Models/Circuit/speed_marker_01_d.dds \
    Media/Models/Circuit/sign_brakevertical_a_01_d.dds \
    Media/Models/Circuit/sign_brakepole100_a_d.dds \
    Media/Models/Circuit/sign_60mphmarker_a_01_d.dds \
    Media/Models/Circuit/santander_brake_a.dds \
    Media/Models/Circuit/safetywall_grey_a_01_d.dds \
    Media/Models/Circuit/poplar_tree_02_tr_d.dds \
    Media/Models/Circuit/poplar_tree_02_shadow.dds \
    Media/Models/Circuit/poplar_tree_02_lod_d.dds \
    Media/Models/Circuit/poplar_tree_02_fo_d.dds \
    Media/Models/Circuit/poplar_tree_02_br_d.dds \
    Media/Models/Circuit/poplar_tree_01_tr_d.dds \
    Media/Models/Circuit/poplar_tree_01_shadow_d.dds \
    Media/Models/Circuit/poplar_tree_01_lod_d.dds \
    Media/Models/Circuit/poplar_tree_01_fo_d.dds \
    Media/Models/Circuit/pit_barrier_white_a.dds \
    Media/Models/Circuit/pirelli_board_a.dds \
    Media/Models/Circuit/pine_tree_01_tr_d.dds \
    Media/Models/Circuit/pine_tree_01_shadow.dds \
    Media/Models/Circuit/pine_tree_01_lod_d.dds \
    Media/Models/Circuit/pine_tree_01_fo_d.dds \
    Media/Models/Circuit/pine_tree_01_br_d.dds \
    Media/Models/Circuit/pffloor_tarmac_a_02_d.dds \
    Media/Models/Circuit/pffloor_tarmac_a_01_d.dds \
    Media/Models/Circuit/oak_tree_03_shadow.dds \
    Media/Models/Circuit/oak_tree_03_lod_d.dds \
    Media/Models/Circuit/oak_tree_02_fo_d.dds \
    Media/Models/Circuit/oak_tree_01_tr_d.dds \
    Media/Models/Circuit/oak_tree_01_fo_d.dds \
    Media/Models/Circuit/monitorstation_white_a_01_d.dds \
    Media/Models/Circuit/mel_tarmac_a_01_d.dds \
    Media/Models/Circuit/marquee_truck_a_01_d.dds \
    Media/Models/Circuit/marquee_a_01_d.dds \
    Media/Models/Circuit/macro_cloth_a_d.dds \
    Media/Models/Circuit/macro_board_blank_d.dds \
    Media/Models/Circuit/macro_board_b_d.dds \
    Media/Models/Circuit/macro_board_a_d.dds \
    Media/Models/Circuit/light_auxrace_a_01_d.dds \
    Media/Models/Circuit/lg_pit_exit_light_a_01_d.dds \
    Media/Models/Circuit/lg_marshal_light_a_01_d.dds \
    Media/Models/Circuit/jumbotron_b_01_d.dds \
    Media/Models/Circuit/hut_marshall_a_d.dds \
    Media/Models/Circuit/hedge_medium_main_b_02_d.dds \
    Media/Models/Circuit/hedge_medium_main_b_01_d.dds \
    Media/Models/Circuit/garage_pit_decal_a_01_d.dds \
    Media/Models/Circuit/garage_low_varq_d.dds \
    Media/Models/Circuit/garage_low_varp_d.dds \
    Media/Models/Circuit/garage_low_varo_d.dds \
    Media/Models/Circuit/garage_low_varn_d.dds \
    Media/Models/Circuit/garage_low_varm_d.dds \
    Media/Models/Circuit/garage_low_varl_d.dds \
    Media/Models/Circuit/garage_low_vark_d.dds \
    Media/Models/Circuit/garage_low_varj_d.dds \
    Media/Models/Circuit/garage_low_vari_d.dds \
    Media/Models/Circuit/garage_low_varh_d.dds \
    Media/Models/Circuit/garage_low_varg_d.dds \
    Media/Models/Circuit/garage_low_varf_d.dds \
    Media/Models/Circuit/garage_low_vare_d.dds \
    Media/Models/Circuit/garage_building_interior_a_01_d.dds \
    Media/Models/Circuit/gantry_start_a_01_d.dds \
    Media/Models/Circuit/flag_scrolling_spa_01_d.dds \
    Media/Models/Circuit/flag_scrolling_mon_01_d.dds \
    Media/Models/Circuit/flag_scrolling_ger_01_d.dds \
    Media/Models/Circuit/flag_scrolling_fer_01_d.dds \
    Media/Models/Circuit/flag_scrolling_eng_01_d.dds \
    Media/Models/Circuit/flag_scrolling_bra_01_d.dds \
    Media/Models/Circuit/flag_scrolling_bla_01_d.dds \
    Media/Models/Circuit/fencekit_a_01_d.dds \
    Media/Models/Circuit/fence_concrete_base_a_mesh_01_d.dds \
    Media/Models/Circuit/fence_concrete_base_a_01_d.dds \
    Media/Models/Circuit/fence_barbed_main_a_mesh_01_d.dds \
    Media/Models/Circuit/fence_barbed_b_01_d.dds \
    Media/Models/Circuit/f1_jumbotron_logo_a_01_d.dds \
    Media/Models/Circuit/eucalyptus_tree_01_tr_d.dds \
    Media/Models/Circuit/eucalyptus_tree_01_shadow.dds \
    Media/Models/Circuit/eucalyptus_tree_01_lod_d.dds \
    Media/Models/Circuit/eucalyptus_tree_01_fo_d.dds \
    Media/Models/Circuit/eucalyptus_tree_01_br_d.dds \
    Media/Models/Circuit/distance_firbeech_02_fo_d.dds \
    Media/Models/Circuit/distance_firbeech_01_fo_d.dds \
    Media/Models/Circuit/dhl_board_a.dds \
    Media/Models/Circuit/core_start_lights_a_01_d.dds \
    Media/Models/Circuit/conc_bollard_filler_a_01_d.dds \
    Media/Models/Circuit/circuit.3ds \
    Media/Models/Circuit/cat_verge_e_d.dds \
    Media/Models/Circuit/cat_verge_d_d.dds \
    Media/Models/Circuit/cat_verge_c_d.dds \
    Media/Models/Circuit/cat_verge_b_d.dds \
    Media/Models/Circuit/cat_verge_a_d.dds \
    Media/Models/Circuit/cat_track_lines_a_01_d.dds \
    Media/Models/Circuit/cat_tarmac_a_03_offtrack_d.dds \
    Media/Models/Circuit/cat_tarmac_a_02_d.dds \
    Media/Models/Circuit/cat_soil_a_d.dds \
    Media/Models/Circuit/cat_rnf_wht_a_d.dds \
    Media/Models/Circuit/cat_rnf_tile_a_d.dds \
    Media/Models/Circuit/cat_rnf_red_a_d.dds \
    Media/Models/Circuit/cat_rnf_grn_wsm_a_d.dds \
    Media/Models/Circuit/cat_rnf_cpt_a_d.dds \
    Media/Models/Circuit/cat_post_tannoy_a_01_d.dds \
    Media/Models/Circuit/cat_pole_wires_a_d.dds \
    Media/Models/Circuit/cat_pole_ranking_a_01_d.dds \
    Media/Models/Circuit/cat_pole_comms_a_01_d.dds \
    Media/Models/Circuit/cat_pole_belltop_a_01_d.dds \
    Media/Models/Circuit/cat_pitwall_a_01_d.dds \
    Media/Models/Circuit/cat_micromacrowsm_01_spons.dds \
    Media/Models/Circuit/cat_macro_grs_d.dds \
    Media/Models/Circuit/cat_landscape_d.dds \
    Media/Models/Circuit/cat_infrastructure_westwall_a_01_d.dds \
    Media/Models/Circuit/cat_infrastructure_weststair_a_01_d.dds \
    Media/Models/Circuit/cat_infrastructure_jumbotron_a_01_d.dds \
    Media/Models/Circuit/cat_infield_a_02_d.dds \
    Media/Models/Circuit/cat_hut_greysweep_a_01_d.dds \
    Media/Models/Circuit/cat_gvl_a_d.dds \
    Media/Models/Circuit/cat_grs_tmc_b_d.dds \
    Media/Models/Circuit/cat_grs_tmc_a_d.dds \
    Media/Models/Circuit/cat_grs_dry_wsm_a_d.dds \
    Media/Models/Circuit/cat_grandstand_vipseats_01_d.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_06_d.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_05_d.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_04_d.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_03_d.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_02_d.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_01_d.dds \
    Media/Models/Circuit/cat_grandstand_lastcorner_a_01_d.dds \
    Media/Models/Circuit/cat_grandstand_hillside_a_02_d.dds \
    Media/Models/Circuit/cat_grandstand_hillside_a_01_d.dds \
    Media/Models/Circuit/cat_grandstand_g_01_d.dds \
    Media/Models/Circuit/cat_grandstand_frameroof_a_01_d.dds \
    Media/Models/Circuit/cat_grandstand_a_04_d.dds \
    Media/Models/Circuit/cat_grandstand_a_03_d.dds \
    Media/Models/Circuit/cat_grandstand_a_02_d.dds \
    Media/Models/Circuit/cat_grandstand_a_01_d.dds \
    Media/Models/Circuit/cat_furniture_hillbench_a_01_d.dds \
    Media/Models/Circuit/cat_flag_01_d.dds \
    Media/Models/Circuit/cat_fea_a_d.dds \
    Media/Models/Circuit/cat_edgestrips_a_d.dds \
    Media/Models/Circuit/cat_details_e_d.dds \
    Media/Models/Circuit/cat_details_d_d.dds \
    Media/Models/Circuit/cat_details_c_d.dds \
    Media/Models/Circuit/cat_details_c_01_d.dds \
    Media/Models/Circuit/cat_details_b_d.dds \
    Media/Models/Circuit/cat_details_a_flat_d.dds \
    Media/Models/Circuit/cat_details_a_d.dds \
    Media/Models/Circuit/cat_cnc_wsm_a_d.dds \
    Media/Models/Circuit/cat_building_villa_a_01_d.dds \
    Media/Models/Circuit/cat_building_podium_a_01_d.dds \
    Media/Models/Circuit/cat_building_pittower_a_01_d.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_06_d.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_05_d.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_04_d.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_03_d.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_02_d.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_01_d.dds \
    Media/Models/Circuit/cat_building_partyhouse_a_01_d.dds \
    Media/Models/Circuit/cat_bridge_west_a_01_d.dds \
    Media/Models/Circuit/cat_bridge_startfinish_a_01_d.dds \
    Media/Models/Circuit/cat_bridge_junction_a_01_d.dds \
    Media/Models/Circuit/cat_barrier_redtarp_a_01_d.dds \
    Media/Models/Circuit/cat_barrier_paddockfrontgate_a_01_d.dds \
    Media/Models/Circuit/cat_barrier_paddockbacgate_a_01_d.dds \
    Media/Models/Circuit/cat_banner_longframe_a_01_d.dds \
    Media/Models/Circuit/cat_banner_greenframe_a_01_d.dds \
    Media/Models/Circuit/camera_scaffold_a_01_d.dds \
    Media/Models/Circuit/brake_white_150_a.dds \
    Media/Models/Circuit/brake_white_100_a.dds \
    Media/Models/Circuit/brake_white_50_a.dds \
    Media/Models/Circuit/brake_drs_a.dds \
    Media/Models/Circuit/brake_black_blank_a.dds \
    Media/Models/Circuit/banner_crowdpartition_a_01_d.dds \
    Media/Models/Circuit/armco_grey_main_a_01_d.dds \
    Media/Models/Circuit/allianz_decal_a.dds \
    Media/Models/Circuit/allianz_brake_a.dds \
    Media/Models/Circuit/advert_side_a_d.dds \
    Media/Models/Cars/Ferrari/tyre_specocc.png \
    Media/Models/Cars/Ferrari/tyre_nm.png \
    Media/Models/Cars/Ferrari/tyre.tga \
    Media/Models/Cars/Ferrari/tyre.png \
    Media/Models/Cars/Ferrari/tread_slick_specocc.png \
    Media/Models/Cars/Ferrari/tread_slick_nm.png \
    Media/Models/Cars/Ferrari/tread_slick.tga \
    Media/Models/Cars/Ferrari/tread_slick.png \
    Media/Models/Cars/Ferrari/light_glow.tga \
    Media/Models/Cars/Ferrari/light_glow.png \
    Media/Models/Cars/Ferrari/int_led.tga \
    Media/Models/Cars/Ferrari/int_led.png \
    Media/Models/Cars/Ferrari/int_info_pod.tga \
    Media/Models/Cars/Ferrari/int_info_pod.png \
    Media/Models/Cars/Ferrari/int_indicator.tga \
    Media/Models/Cars/Ferrari/int_indicator.png \
    Media/Models/Cars/Ferrari/int_fe0_main.tga \
    Media/Models/Cars/Ferrari/int_fe0_main.png \
    Media/Models/Cars/Ferrari/int_digi_tach.tga \
    Media/Models/Cars/Ferrari/int_digi_tach.png \
    Media/Models/Cars/Ferrari/int_digi_placeholder.tga \
    Media/Models/Cars/Ferrari/int_digi_placeholder.png \
    Media/Models/Cars/Ferrari/glass.tga \
    Media/Models/Cars/Ferrari/glass.png \
    Media/Models/Cars/Ferrari/generic_main_specocc.png \
    Media/Models/Cars/Ferrari/generic_main_nm.png \
    Media/Models/Cars/Ferrari/generic_main.tga \
    Media/Models/Cars/Ferrari/generic_main.png \
    Media/Models/Cars/Ferrari/ferrari.3ds \
    Media/Models/Cars/Ferrari/fe0_wheel.tga \
    Media/Models/Cars/Ferrari/fe0_wheel.png \
    Media/Models/Cars/Ferrari/fe0_main.tga \
    Media/Models/Cars/Ferrari/fe0_main.png \
    Media/Models/Circuit/vpower_board_a.dds \
    Media/Models/Circuit/universal_2d_refmap.dds \
    Media/Models/Circuit/ubs_terrain_a.dds \
    Media/Models/Circuit/track_weteffects.dds \
    Media/Models/Circuit/track_skidmarks_long.dds \
    Media/Models/Circuit/track_marbles.dds \
    Media/Models/Circuit/track_macro_a_02_d.dds \
    Media/Models/Circuit/step_ladder_01_a.dds \
    Media/Models/Circuit/standee_parcfermeplace_a_01_s.dds \
    Media/Models/Circuit/sponsorx_cats_varpb_d.dds \
    Media/Models/Circuit/sponsor_racc_floor_01_d.dds \
    Media/Models/Circuit/sponsor_circuit_catalunya_a_02_d.dds \
    Media/Models/Circuit/sponsor_circuit_catalunya_a_01_d.dds \
    Media/Models/Circuit/sponsor_backboard_01.dds \
    Media/Models/Circuit/speed_marker_01_a.dds \
    Media/Models/Circuit/sign_brakevertical_a_01_s.dds \
    Media/Models/Circuit/sign_brakevertical_a_01_a.dds \
    Media/Models/Circuit/sign_brakepole100_a_s.dds \
    Media/Models/Circuit/sign_brakepole100_a_a.dds \
    Media/Models/Circuit/sign_60mphmarker_a_01_s.dds \
    Media/Models/Circuit/sign_60mphmarker_a_01_a.dds \
    Media/Models/Circuit/santander_terrain_a.dds \
    Media/Models/Circuit/santander_a.dds \
    Media/Models/Circuit/safetywall_grey_a_01_s.dds \
    Media/Models/Circuit/randomnoise.dds \
    Media/Models/Circuit/rack_nosecone_a_01_a.dds \
    Media/Models/Circuit/pzero_board_a.dds \
    Media/Models/Circuit/poplar_tree_02_lod_n.dds \
    Media/Models/Circuit/poplar_tree_01_lod_n.dds \
    Media/Models/Circuit/placeholder_ipr.dds \
    Media/Models/Circuit/pit_barrier_white_a_s.dds \
    Media/Models/Circuit/pit_barrier_white_a_n.dds \
    Media/Models/Circuit/pit_barrier_white_a_a.dds \
    Media/Models/Circuit/pirelli_terrain_a.dds \
    Media/Models/Circuit/pine_tree_01_lod_n.dds \
    Media/Models/Circuit/physical_tyres_base_a_01_s.dds \
    Media/Models/Circuit/physical_tyres_a_01_a.dds \
    Media/Models/Circuit/pffloor_tarmac_a_02_s.dds \
    Media/Models/Circuit/parcferme_macro.dds \
    Media/Models/Circuit/oak_tree_03_lod_n.dds \
    Media/Models/Circuit/monitorstation_white_c_01_a.dds \
    Media/Models/Circuit/monitorstation_white_a_02_s.dds \
    Media/Models/Circuit/monitorstation_white_a_01_s.dds \
    Media/Models/Circuit/mel_tarmac_a_01_n.dds \
    Media/Models/Circuit/marquee_truck_a_a.dds \
    Media/Models/Circuit/marquee_truck_a_01_s.dds \
    Media/Models/Circuit/marquee_sml_b_01_a.dds \
    Media/Models/Circuit/marquee_sml_a_01_a.dds \
    Media/Models/Circuit/marquee_a_01_s.dds \
    Media/Models/Circuit/macro_cloth_a_s.dds \
    Media/Models/Circuit/macro_board_b_s.dds \
    Media/Models/Circuit/macro_board_a_s.dds \
    Media/Models/Circuit/macro_block_a_d.dds \
    Media/Models/Circuit/lowgarage_team_lm_02.dds \
    Media/Models/Circuit/lowgarage_team_lm_01.dds \
    Media/Models/Circuit/light_pole_a_a.dds \
    Media/Models/Circuit/light_auxrace_a_01_s.dds \
    Media/Models/Circuit/light_auxrace_a_01_a.dds \
    Media/Models/Circuit/lg_pit_exit_light_a_01_s.dds \
    Media/Models/Circuit/lg_pit_exit_light_a_01_a.dds \
    Media/Models/Circuit/lg_marshal_light_a_01_s.dds \
    Media/Models/Circuit/lg_marshal_light_a_01_a.dds \
    Media/Models/Circuit/lg_board_a.dds \
    Media/Models/Circuit/jumbotron_screeneffect_d.dds \
    Media/Models/Circuit/jumbotron_b_a_a.dds \
    Media/Models/Circuit/jumbotron_b_01_s.dds \
    Media/Models/Circuit/hut_marshall_a_s.dds \
    Media/Models/Circuit/hut_marshall_a_01_a.dds \
    Media/Models/Circuit/hedge_medium_main_b_02_s.dds \
    Media/Models/Circuit/generic_occlusion_01_a.dds \
    Media/Models/Circuit/garage_team_reflection_a_01_d.dds \
    Media/Models/Circuit/garage_team_colour_a_01_s.dds \
    Media/Models/Circuit/garage_team_a.dds \
    Media/Models/Circuit/garage_pit_decal_a_01_s.dds \
    Media/Models/Circuit/garage_building_interior_a_01_s.dds \
    Media/Models/Circuit/garage_building_interior_a_01_n.dds \
    Media/Models/Circuit/garage_building_interior_a_01_a.dds \
    Media/Models/Circuit/garage_building_a.dds \
    Media/Models/Circuit/gantry_overhang_a_01_a.dds \
    Media/Models/Circuit/fencekit_a_01_s.dds \
    Media/Models/Circuit/fence_concrete_base_a_01_s.dds \
    Media/Models/Circuit/fence_concrete_base_a_01_a.dds \
    Media/Models/Circuit/fence_barbed_main_a_mesh_01_s.dds \
    Media/Models/Circuit/fence_barbed_b_01_s.dds \
    Media/Models/Circuit/eucalyptus_tree_01_lod_n.dds \
    Media/Models/Circuit/eni_terrain_a.dds \
    Media/Models/Circuit/eni_board_a.dds \
    Media/Models/Circuit/defaultrefmap.dds \
    Media/Models/Circuit/default_ao_terrain.dds \
    Media/Models/Circuit/default_ao.dds \
    Media/Models/Circuit/crowd_flag_lrg_a_03_s.dds \
    Media/Models/Circuit/core_start_lights_gantry_a_a.dds \
    Media/Models/Circuit/core_start_lights_a_01_s.dds \
    Media/Models/Circuit/core_start_lights_a_01_a.dds \
    Media/Models/Circuit/conc_bollard_filler_a_01_s.dds \
    Media/Models/Circuit/cat_verge_e_n.dds \
    Media/Models/Circuit/cat_verge_d_n.dds \
    Media/Models/Circuit/cat_verge_c_n.dds \
    Media/Models/Circuit/cat_verge_b_n.dds \
    Media/Models/Circuit/cat_verge_a_n.dds \
    Media/Models/Circuit/cat_tracksurface_n.dds \
    Media/Models/Circuit/cat_track_lines_a_01_s.dds \
    Media/Models/Circuit/cat_track_lines_a_01_n.dds \
    Media/Models/Circuit/cat_tarmac_new_wsm_a_s.dds \
    Media/Models/Circuit/cat_tarmac_new_wsm_a_d.dds \
    Media/Models/Circuit/cat_rnf_tile_a_n.dds \
    Media/Models/Circuit/cat_rnf_red_a_s.dds \
    Media/Models/Circuit/cat_rnf_red_a_n.dds \
    Media/Models/Circuit/cat_rnf_grn_wsm_b_d.dds \
    Media/Models/Circuit/cat_rnf_grn_wsm_a_s.dds \
    Media/Models/Circuit/cat_rnf_cpt_a_n.dds \
    Media/Models/Circuit/cat_post_tannoy_a_01_a.dds \
    Media/Models/Circuit/cat_pole_wires_a_s.dds \
    Media/Models/Circuit/cat_pole_wires_a_01_a.dds \
    Media/Models/Circuit/cat_pole_ranking_a_01_s.dds \
    Media/Models/Circuit/cat_pole_ranking_a_01_a.dds \
    Media/Models/Circuit/cat_pole_comms_a_01_s.dds \
    Media/Models/Circuit/cat_pole_comms_a_01_a.dds \
    Media/Models/Circuit/cat_pole_belltop_a_01_a.dds \
    Media/Models/Circuit/cat_pitwall_a_01_s.dds \
    Media/Models/Circuit/cat_pitwall_a_01_n.dds \
    Media/Models/Circuit/cat_pitwall_a_01_a.dds \
    Media/Models/Circuit/cat_micromacrowsm_01_d.dds \
    Media/Models/Circuit/cat_macro_terrain_01_d.dds \
    Media/Models/Circuit/cat_macro_shine_d.dds \
    Media/Models/Circuit/cat_infrastructure_westwall_a_01_a.dds \
    Media/Models/Circuit/cat_infrastructure_weststair_a_01_s.dds \
    Media/Models/Circuit/cat_infrastructure_weststair_a_01_a.dds \
    Media/Models/Circuit/cat_infrastructure_rockbolster_a_01_a.dds \
    Media/Models/Circuit/cat_infrastructure_jumbotron_a_01_s.dds \
    Media/Models/Circuit/cat_infrastructure_jumbotron_a_01_a.dds \
    Media/Models/Circuit/cat_infield_b_01_d.dds \
    Media/Models/Circuit/cat_infield_a_02_s.dds \
    Media/Models/Circuit/cat_hut_greysweep_a_01_s.dds \
    Media/Models/Circuit/cat_hut_greysweep_a_01_a.dds \
    Media/Models/Circuit/cat_hut_greyplatform_a_01_a.dds \
    Media/Models/Circuit/cat_gvl_wsm_a_s.dds \
    Media/Models/Circuit/cat_gvl_wsm_a_d.dds \
    Media/Models/Circuit/cat_gvl_a_s.dds \
    Media/Models/Circuit/cat_grs_dry_wsm_a_n.dds \
    Media/Models/Circuit/cat_grandstand_vipseats_a_01_a.dds \
    Media/Models/Circuit/cat_grandstand_twosided_a_01_a.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_04_s.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_03_s.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_02_s.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_01_s.dds \
    Media/Models/Circuit/cat_grandstand_tribuna_a_01_a.dds \
    Media/Models/Circuit/cat_grandstand_o_01_a.dds \
    Media/Models/Circuit/cat_grandstand_n_01_a.dds \
    Media/Models/Circuit/cat_grandstand_m_01_a.dds \
    Media/Models/Circuit/cat_grandstand_lastcorner_a_01_s.dds \
    Media/Models/Circuit/cat_grandstand_lastcorner_a_01_a.dds \
    Media/Models/Circuit/cat_grandstand_l_01_a.dds \
    Media/Models/Circuit/cat_grandstand_j_01_a_.dds \
    Media/Models/Circuit/cat_grandstand_i_01_a.dds \
    Media/Models/Circuit/cat_grandstand_hillside_a_02_s.dds \
    Media/Models/Circuit/cat_grandstand_hillside_a_02_n.dds \
    Media/Models/Circuit/cat_grandstand_hillside_a_01_s.dds \
    Media/Models/Circuit/cat_grandstand_hillside_a_01_n.dds \
    Media/Models/Circuit/cat_grandstand_hillside_a_01_a.dds \
    Media/Models/Circuit/cat_grandstand_h_01_a.dds \
    Media/Models/Circuit/cat_grandstand_g_01_a.dds \
    Media/Models/Circuit/cat_grandstand_frameroof_a_01_s.dds \
    Media/Models/Circuit/cat_grandstand_frameroof_a_01_n.dds \
    Media/Models/Circuit/cat_grandstand_frameroof_a_01_a.dds \
    Media/Models/Circuit/cat_grandstand_f_01_a.dds \
    Media/Models/Circuit/cat_grandstand_e_01_a.dds \
    Media/Models/Circuit/cat_grandstand_doubledeck_a_01_a.dds \
    Media/Models/Circuit/cat_grandstand_d_01_a.dds \
    Media/Models/Circuit/cat_grandstand_c_01_a.dds \
    Media/Models/Circuit/cat_grandstand_b_01_a.dds \
    Media/Models/Circuit/cat_grandstand_a_01_s.dds \
    Media/Models/Circuit/cat_grandstand_a_01_a.dds \
    Media/Models/Circuit/cat_generic_flat_normal_n.dds \
    Media/Models/Circuit/cat_furniture_redbin_a_01_a.dds \
    Media/Models/Circuit/cat_furniture_hillbench_a_01_a.dds \
    Media/Models/Circuit/cat_edgestrips_a_s.dds \
    Media/Models/Circuit/cat_edgestrips_a_n.dds \
    Media/Models/Circuit/cat_details_e_n.dds \
    Media/Models/Circuit/cat_details_d_n.dds \
    Media/Models/Circuit/cat_details_c_n.dds \
    Media/Models/Circuit/cat_details_c_01_n.dds \
    Media/Models/Circuit/cat_details_b_n.dds \
    Media/Models/Circuit/cat_details_a_n.dds \
    Media/Models/Circuit/cat_cnc_wsm_a_s.dds \
    Media/Models/Circuit/cat_building_villa_a_01_s.dds \
    Media/Models/Circuit/cat_building_villa_a_01_a.dds \
    Media/Models/Circuit/cat_building_podium_a_01_s.dds \
    Media/Models/Circuit/cat_building_podium_a_01_n.dds \
    Media/Models/Circuit/cat_building_podium_a_01_a.dds \
    Media/Models/Circuit/cat_building_pittower_a_01_s.dds \
    Media/Models/Circuit/cat_building_pittower_a_01_a.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_06_s.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_06_n.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_05_s.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_05_n.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_04_s.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_04_n.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_03_s.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_03_n.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_02_s.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_02_n.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_01_s.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_01_n.dds \
    Media/Models/Circuit/cat_building_pitgarages_a_01_a.dds \
    Media/Models/Circuit/cat_building_partyhouse_a_01_s.dds \
    Media/Models/Circuit/cat_building_partyhouse_a_01_a.dds \
    Media/Models/Circuit/cat_bridge_west_a_01_s.dds \
    Media/Models/Circuit/cat_bridge_west_a_01_n.dds \
    Media/Models/Circuit/cat_bridge_west_a_01_a.dds \
    Media/Models/Circuit/cat_bridge_startfinish_a_01_s.dds \
    Media/Models/Circuit/cat_bridge_startfinish_a_01_a.dds \
    Media/Models/Circuit/cat_bridge_junction_a_01_a.dds \
    Media/Models/Circuit/cat_bridge_hillcross_a_01_a.dds \
    Media/Models/Circuit/cat_blend_c.dds \
    Media/Models/Circuit/cat_blend_b.dds \
    Media/Models/Circuit/cat_barrier_redtarp_a_01_s.dds \
    Media/Models/Circuit/cat_barrier_paddockfrontgate_a_01_s.dds \
    Media/Models/Circuit/cat_barrier_paddockfrontgate_a_01_a.dds \
    Media/Models/Circuit/cat_barrier_paddockbacgate_a_01_s.dds \
    Media/Models/Circuit/cat_barrier_paddockbacgate_a_01_a.dds \
    Media/Models/Circuit/cat_banner_longframe_a_01_s.dds \
    Media/Models/Circuit/cat_banner_longframe_a_01_a.dds \
    Media/Models/Circuit/cat_banner_greenframe_a_01_s.dds \
    Media/Models/Circuit/cat_banner_greenframe_a_01_a.dds \
    Media/Models/Circuit/cat_ao_terrain_01_d.dds \
    Media/Models/Circuit/camera_scaffold_a_x2_a.dds \
    Media/Models/Circuit/camera_scaffold_a_01_s.dds \
    Media/Models/Circuit/banner_crowdpartition_a_01_s.dds \
    Media/Models/Circuit/armco_grey_main_a_01_s.dds \
    Media/Models/Circuit/allianz_terrain_a.dds \
    Media/Models/Circuit/allianz_board_b.dds \
    Media/Models/Circuit/allianz_board_a.dds \
    Media/Models/Circuit/advert_side_a_s.dds \
    Media/Models/Circuit/advert_side_a_a.dds \
    Media/Models/Cars/Ferrari/wheelRearRight.3ds \
    Media/Models/Cars/Ferrari/wheelRearLeft.3ds \
    Media/Models/Cars/Ferrari/wheelFrontRight.3ds \
    Media/Models/Cars/Ferrari/wheelFrontLeft.3ds \
    Media/Models/Cars/Ferrari/Wheel.lwo \
    Media/Models/Cars/Ferrari/wheel4.tga \
    Media/Models/Cars/Ferrari/wheel3.tga \
    Media/Models/Cars/Ferrari/wheel2.tga \
    Media/Models/Cars/Ferrari/wheel.3ds \
    Media/Models/Cars/Ferrari/digi6.tga \
    Media/Models/Cars/Ferrari/digi5.tga \
    Media/Models/Cars/Ferrari/digi4.tga \
    Media/Models/Cars/Ferrari/digi3.tga \
    Media/Models/Cars/Ferrari/digi2.tga \
    Media/Models/Cars/Ferrari/digi1.tga \
    Media/Models/Cars/Ferrari/chasis2.tga \
    Media/Models/Cars/Ferrari/chasis.tga \
    Media/Models/Cars/Ferrari/chasis.3ds \
    Media/Models/Sky/sky.3ds \
    Media/Models/Sky/cat_sky_sun_01.dds \
    Media/Images/1365553386_export.png \
    Media/Images/1365553346_import.png \
    Media/Images/1365553596_idea.png \
    Media/Images/1365553750_film_camera_35mm.png \
    Media/Images/1365559690_single_seater.png \
    Media/Images/1365560323_Gear.png \
    Media/Images/1365559833_tyres.png \
    Media/Images/1365728458_Warning.png \
    Media/Models/Circuit/forest4.3ds \
    Media/Models/Circuit/forest3.3ds \
    Media/Models/Circuit/forest2.3ds \
    Media/Models/Circuit/forest1.3ds \
    Media/Models/Circuit/terrain.3ds \
    Media/Models/Circuit/gradas1.3ds \
    Media/Models/Circuit/gradas2.3ds \
    Media/Models/Circuit/gradas3.3ds \
    Media/Models/Circuit/gradas4.3ds \
    Media/Models/Circuit/gradas5.3ds \
    Media/Models/Circuit/gradas6.3ds \
    Media/Models/Circuit/gradas7.3ds \
    Media/Models/Circuit/gradas8.3ds \
    Media/Models/Circuit/vallas.3ds \
    Media/Models/Circuit/objects1.3ds \
    Media/Models/Circuit/drs_w029.dds \
    Media/Models/Circuit/gantr064.dds \
    Media/Models/Circuit/clear120.dds \
    Media/Models/Circuit/cat_p021.dds \
    Media/Models/Circuit/cat_i001.dds \
    Media/Models/Circuit/cat_g054.dds \
    Media/Models/Circuit/cat_g113.dds \
    Media/Models/Circuit/cat_b115.dds \
    Media/Models/Circuit/fence152.dds \
    Media/Models/Circuit/cat_b112.dds \
    Media/Models/Circuit/pirel015.dds \
    Media/Models/Circuit/lg_bo012.dds \
    Media/Models/Circuit/santa019.dds \
    Media/Models/Circuit/armco107.dds \
    Media/Models/Circuit/ubs_b004.dds \
    Media/Models/Circuit/flag_106.dds \
    Media/Models/Circuit/flag_092.dds \
    Media/Models/Circuit/flag_091.dds \
    Media/Models/Circuit/dhl_b014.dds \
    Media/Models/Circuit/flag_100.dds \
    Media/Models/Circuit/flag_095.dds \
    Media/Models/Circuit/flag_085.dds \
    Media/Models/Circuit/cat_g114.dds \
    Media/Models/Circuit/cat_g112.dds \
    Media/Models/Circuit/flag_079.dds \
    Media/Models/Circuit/cat_p103.dds \
    Media/Models/Circuit/fence134.dds \
    Media/Models/Circuit/fence125.dds \
    Media/Models/Circuit/hut_m023.dds \
    Media/Models/Circuit/eni_b010.dds \
    Media/Models/Circuit/cat_p102.dds \
    Media/Models/Circuit/allia009.dds \
    Media/Models/Circuit/speed098.dds \
    Media/Models/Circuit/safet069.dds \
    Media/Models/Circuit/allia010.dds \
    Media/Models/Circuit/spons064.dds \
    Media/Models/Circuit/spons022.dds \
    Media/Models/Circuit/hedge130.dds \
    Media/Models/Circuit/hedge131.dds \
    Media/Models/Circuit/light105.dds \
    Media/Models/Circuit/cat_b138.dds \
    Media/Models/Circuit/cat_b055.dds \
    Media/Models/Circuit/sign_154.dds \
    Media/Models/Circuit/santa013.dds \
    Media/Models/Circuit/brake157.dds \
    Media/Models/Circuit/ubs_d011.dds \
    Media/Models/Circuit/cat_h067.dds \
    Media/Models/Circuit/cat_d052.dds \
    Media/Models/Circuit/cat_d037.dds \
    Media/Models/Circuit/brake162.dds \
    Media/Models/Circuit/brake103.dds \
    Media/Models/Circuit/sign_093.dds \
    Media/Models/Circuit/cat_p066.dds \
    Media/Models/Circuit/cat_d035.dds \
    Media/Models/Circuit/marqu111.dds \
    Media/Models/Circuit/spons021.dds \
    Media/Models/Circuit/pzero028.dds \
    Media/Models/Circuit/vpowe040.dds \
    Media/Models/Circuit/cat_g068.dds \
    Media/Models/Circuit/cat_b121.dds \
    Media/Models/Circuit/adver004.dds \
    Media/Models/Circuit/cat_p110.dds \
    Media/Models/Circuit/cat_i011.dds \
    Media/Models/Circuit/gs_cl014.dds \
    Media/Models/Circuit/conc_116.dds \
    Media/Models/Circuit/cat_g100.dds \
    Media/Models/Circuit/cat_b085.dds \
    Media/Models/Circuit/cat_g101.dds \
    Media/Models/Circuit/cat_f076.dds \
    Media/Models/Circuit/cat_b113.dds \
    Media/Models/Circuit/lg_pi086.dds \
    Media/Models/Circuit/cat_p107.dds \
    Media/Models/Circuit/cat_g109.dds \
    Media/Models/Circuit/cat_g089.dds \
    Media/Models/Circuit/cat_f135.dds \
    Media/Models/Circuit/toile025.dds \
    Media/Models/Circuit/f1_ju127.dds \
    Media/Models/Circuit/cat_b102.dds \
    Media/Models/Circuit/jumbo076.dds \
    Media/Models/Circuit/garag147.dds \
    Media/Models/Circuit/team_065.dds \
    Media/Models/Circuit/pit_p093.dds \
    Media/Models/Circuit/garag087.dds \
    Media/Models/Circuit/garag022.dds \
    Media/Models/Circuit/garag021.dds \
    Media/Models/Circuit/garag020.dds \
    Media/Models/Circuit/garag019.dds \
    Media/Models/Circuit/pit_p111.dds \
    Media/Models/Circuit/garag024.dds \
    Media/Models/Circuit/garag023.dds \
    Media/Models/Circuit/garag017.dds \
    Media/Models/Circuit/cat_b086.dds \
    Media/Models/Circuit/dista069.dds \
    Media/Models/Circuit/dista038.dds \
    Media/Models/Circuit/unive003.dds \
    Media/Models/Circuit/pit_p077.dds \
    Media/Models/Circuit/core_069.dds \
    Media/Models/Circuit/pit_p106.dds \
    Media/Models/Circuit/cat_g083.dds \
    Media/Models/Circuit/cat_g082.dds \
    Media/Models/Circuit/cat_g084.dds \
    Media/Models/Circuit/cat_g085.dds \
    Media/Models/Circuit/cat_g086.dds \
    Media/Models/Circuit/cat_g115.dds \
    Media/Models/Circuit/cat_g087.dds \
    Media/Models/Circuit/cat_b063.dds \
    Media/Models/Circuit/cat_b095.dds \
    Media/Models/Circuit/cat_b097.dds \
    Media/Models/Circuit/cat_b098.dds \
    Media/Models/Circuit/cat_b099.dds \
    Media/Models/Circuit/cat_b100.dds \
    Media/Models/Circuit/pit_p036.dds \
    Media/Models/Circuit/stand107.dds \
    Media/Models/Circuit/pit_p074.dds \
    Media/Models/Circuit/garag027.dds \
    Media/Models/Circuit/garag026.dds \
    Media/Models/Circuit/garag025.dds \
    Media/Models/Circuit/lg_ma109.dds \
    Media/Models/Circuit/sign_193.dds \
    Media/Models/Circuit/pit_p095.dds \
    Media/Models/Circuit/camer141.dds \
    Media/Models/Circuit/allia006.dds \
    Media/Models/Circuit/pit_p067.dds \
    Media/Models/Circuit/cat_b096.dds \
    Media/Models/Circuit/banne051.dds \
    Media/Models/Circuit/spons082.dds \
    Media/Models/Circuit/pit_p103.dds \
    Media/Models/Circuit/spons102.dds \
    Media/Models/Circuit/pit_p102.dds \
    Media/Models/Circuit/cat_i005.dds \
    Media/Models/Circuit/pit_p113.dds \
    Media/Models/Circuit/pit_p094.dds \
    Media/Models/Circuit/oak_t077.dds \
    Media/Models/Circuit/macro002.dds \
    Media/Models/Circuit/garag029.dds \
    Media/Models/Circuit/garag028.dds \
    Media/Models/Circuit/garag018.dds \
    Media/Models/Circuit/fence161.dds \
    Media/Models/Circuit/oak_t111.dds \
    Media/Models/Circuit/oak_t110.dds \
    Media/Models/Circuit/oak_t106.dds \
    Media/Models/Circuit/oak_t094.dds \
    Media/Models/Circuit/popla060.dds \
    Media/Models/Circuit/dista118.dds \
    Media/Models/Circuit/dista117.dds \
    Media/Models/Circuit/popla078.dds \
    Media/Models/Circuit/popla077.dds \
    Media/Models/Circuit/popla064.dds \
    Media/Models/Circuit/popla048.dds \
    Media/Models/Circuit/popla080.dds \
    Media/Models/Circuit/popla081.dds \
    Media/Models/Circuit/popla063.dds \
    Media/Models/Circuit/eucal041.dds \
    Media/Models/Circuit/eucal012.dds \
    Media/Models/Circuit/eucal044.dds \
    Media/Models/Circuit/eucal045.dds \
    Media/Models/Circuit/eucal027.dds \
    Media/Models/Circuit/cat_t132.dds \
    Media/Models/Circuit/cat_i136.dds \
    Media/Models/Circuit/cat_s003.dds \
    Media/Models/Circuit/cat_c005.dds \
    Media/Models/Circuit/cat_g010.dds \
    Media/Models/Circuit/cat_g009.dds \
    Media/Models/Circuit/cat_t133.dds \
    Media/Models/Circuit/cat_d124.dds \
    Media/Models/Circuit/cat_d007.dds \
    Media/Models/Circuit/cat_d005.dds \
    Media/Models/Circuit/cat_w025.dds \
    Media/Models/Circuit/cat_d006.dds \
    Media/Models/Circuit/cat_r023.dds \
    Media/Models/Circuit/cat_f039.dds \
    Media/Models/Circuit/cat_r015.dds \
    Media/Models/Circuit/cat_o098.dds \
    Media/Models/Circuit/cat_g037.dds \
    Media/Models/Circuit/cat_r009.dds \
    Media/Models/Circuit/cat_g000.dds \
    Media/Models/Circuit/cat_d008.dds \
    Media/Models/Circuit/cat_r003.dds \
    Media/Models/Circuit/cat_e022.dds \
    Media/Models/Circuit/cat_v008.dds \
    Media/Models/Circuit/cat_v007.dds \
    Media/Models/Circuit/cat_m014.dds \
    Media/Models/Circuit/cat_v004.dds \
    Media/Models/Circuit/cat_g001.dds \
    Media/Models/Circuit/cat_v005.dds \
    Media/Models/Circuit/cat_v006.dds \
    Media/Models/Circuit/buildings2.3ds \
    Media/Models/Circuit/buildings3.3ds \
    Media/Models/Circuit/buildings4.3ds \
    Media/Models/Circuit/vallasPlastico.3ds \
    Media/Models/Circuit/vegetacion.3ds \
    Media/Models/Circuit/buildings1_1.3ds \
    Media/Models/Circuit/buildings1_2.3ds \
    Media/Models/Circuit/buildings1_3.3ds \
    Media/Models/Circuit/buildings1_4.3ds \
    Media/Models/Circuit/buildings1_5.3ds \
    Media/Models/Circuit/buildings1_6.3ds \
    Media/Models/Circuit/buildings1_8.3ds \
    Media/Models/Circuit/buildings1_7.3ds \
    Media/Models/Circuit/buildings1_11.3ds \
    Media/Models/Circuit/buildings1_10.3ds \
    Media/Models/Circuit/buildings1_12.3ds \
    Media/Models/Circuit/buildings1_9.3ds \
    Media/Models/Circuit/buildings2_1.3ds \
    Media/Models/Circuit/buildings2_2.3ds \
    Media/Models/Circuit/buildings2_3.3ds \
    Media/Models/Circuit/buildings2_4.3ds \
    Media/Models/Circuit/buildings3_1.3ds \
    Media/Models/Circuit/buildings3_2.3ds \
    Media/Models/Circuit/buildings3_3.3ds \
    Media/Models/Circuit/buildings3_6.3ds \
    Media/Models/Circuit/buildings4_1.3ds \
    Media/Models/Circuit/buildings4_2.3ds \
    Media/Models/Circuit/buildings3_7.3ds \
    Media/Models/Circuit/buildings3_4.3ds \
    Media/Models/Circuit/buildings3_5.3ds \
    Media/Models/Circuit/banderas_1.3ds \
    Media/Models/Circuit/banderas_2.3ds \
    Media/Models/Circuit/banderas_3.3ds \
    Media/Models/Circuit/banderas_4.3ds \
    Media/Models/Circuit/banderas_5.3ds \
    Media/Models/Circuit/banderas_6.3ds \
    Media/Models/Circuit/banderas_7.3ds \
    Media/Models/Circuit/banderas_8.3ds \
    Media/Models/Circuit/banderas_9.3ds \
    Media/Models/Circuit/banderas_10.3ds \
    Media/Models/Circuit/banderas_11.3ds \
    Media/Models/Circuit/banderas_12.3ds \
    Media/Models/Circuit/banderas_13.3ds \
    Media/Models/Circuit/banderas_15.3ds \
    Media/Models/Circuit/banderas_14.3ds \
    Media/Models/Circuit/banderas_16.3ds \
    Media/Models/Circuit/banderas_17.3ds \
    Media/Models/Circuit/barreras_1.3ds \
    Media/Models/Circuit/barreras_2.3ds \
    Media/Models/Circuit/barreras_3.3ds \
    Media/Models/Circuit/barreras_4.3ds \
    Media/Models/Circuit/barreras_5.3ds \
    Media/Models/Circuit/barreras_6.3ds \
    Media/Models/Circuit/barreras_7.3ds \
    Media/Models/Circuit/barreras_8.3ds \
    Media/Models/Circuit/barreras_9.3ds \
    Media/Models/Circuit/barreras_10.3ds \
    Media/Models/Circuit/barreras_11.3ds \
    Media/Models/Circuit/barreras_12.3ds \
    Media/Models/Circuit/barreras_13.3ds \
    Media/Models/Circuit/barreras_14.3ds \
    Media/Models/Circuit/barreras_15.3ds \
    Media/Models/Circuit/objects_1.3ds \
    Media/Models/Circuit/objects_2.3ds \
    Media/Models/Circuit/objects_3.3ds \
    Media/Models/Circuit/objects_4.3ds \
    Media/Models/Circuit/objects_5.3ds \
    Media/Models/Circuit/objects_6.3ds \
    Media/Models/Circuit/objects_7.3ds \
    Media/Models/Circuit/objects_8.3ds \
    Media/Models/Circuit/objects_9.3ds \
    Media/Models/Circuit/objects_10.3ds \
    Media/Models/Circuit/objects_11.3ds \
    Media/Models/Circuit/objects_12.3ds \
    Media/Models/Circuit/objects_13.3ds \
    Media/Models/Circuit/objects_14.3ds \
    Media/Models/Circuit/objects_15.3ds \
    Media/Models/Circuit/objects_16.3ds \
    Media/Models/Circuit/objects_17.3ds \
    Media/Models/Circuit/objects_18.3ds \
    Media/Models/Circuit/objects_19.3ds \
    Media/Models/Circuit/objects_20.3ds \
    Media/Models/Circuit/vallas_1.3ds \
    Media/Models/Circuit/vallas_2.3ds \
    Media/Models/Circuit/vallas_3.3ds \
    Media/Models/Circuit/vallas_4.3ds \
    Media/Models/Circuit/vallas_5.3ds \
    Media/Models/Circuit/vallas_6.3ds \
    Media/Models/Circuit/vallas_7.3ds \
    Media/Models/Circuit/vallas_8.3ds \
    Media/Models/Circuit/vallas_9.3ds \
    Media/Models/Circuit/vallas_10.3ds \
    Media/Models/Circuit/vallas_11.3ds \
    Media/Models/Circuit/vallas_12.3ds \
    Media/Models/Circuit/vallas_13.3ds \
    Media/Models/Circuit/vallas_14.3ds \
    Media/Models/Circuit/vallas_15.3ds \
    Media/Models/Circuit/vallas_16.3ds \
    Media/Models/Circuit/vallas_17.3ds \
    Media/Models/Circuit/vallas_18.3ds \
    Media/Models/Circuit/vallas_19.3ds \
    Media/Models/Circuit/vallas_20.3ds \
    Media/Models/Circuit/vallas_21.3ds \
    Media/Models/Circuit/vallas_22.3ds \
    Media/Models/Circuit/vallas_23.3ds \
    Media/Models/Circuit/vallas_24.3ds \
    Media/Models/Circuit/vallas_25.3ds \
    Media/Models/Circuit/vallas_26.3ds \
    Media/Models/Circuit/vallas_27.3ds \
    Media/Models/Circuit/vallas_28.3ds \
    Media/Models/Circuit/vegetacion_1.3ds \
    Media/Models/Circuit/vegetacion_2.3ds \
    Media/Models/Circuit/vegetacion_3.3ds \
    Media/Models/Circuit/vegetacion_4.3ds \
    Media/Models/Circuit/vegetacion_5.3ds \
    Media/Models/Circuit/vegetacion_6.3ds \
    Media/Models/Circuit/vegetacion_7.3ds \
    Media/Models/Circuit/vegetacion_8.3ds \
    Media/Models/Circuit/vegetacion_9.3ds \
    Media/Models/Circuit/vegetacion_10.3ds \
    Media/Models/Circuit/vegetacion_11.3ds \
    Media/Models/Circuit/vegetacion_12.3ds \
    Media/Models/Circuit/vegetacion_13.3ds \
    Media/Models/Circuit/vegetacion_14.3ds \
    Media/Models/Circuit/vegetacion_15.3ds \
    Media/Models/Circuit/vegetacion_16.3ds \
    Media/Models/Circuit/vegetacion_17.3ds \
    Media/Models/Circuit/vegetacion_18.3ds \
    Media/Models/Circuit/vegetacion_19.3ds \
    Media/Models/Circuit/vegetacion_20.3ds \
    Media/Models/Circuit/vegetacion_21.3ds \
    Media/Models/Circuit/vegetacion_22.3ds \
    Media/Models/Circuit/vegetacion_23.3ds \
    Media/Models/Circuit/vegetacion_24.3ds \
    Media/Models/Circuit/vegetacion_25.3ds \
    Media/Models/Circuit/vallasPlastico_40.3ds \
    Media/Models/Circuit/vallasPlastico_39.3ds \
    Media/Models/Circuit/vallasPlastico_38.3ds \
    Media/Models/Circuit/vallasPlastico_37.3ds \
    Media/Models/Circuit/vallasPlastico_36.3ds \
    Media/Models/Circuit/vallasPlastico_35.3ds \
    Media/Models/Circuit/vallasPlastico_34.3ds \
    Media/Models/Circuit/vallasPlastico_33.3ds \
    Media/Models/Circuit/vallasPlastico_32.3ds \
    Media/Models/Circuit/vallasPlastico_31.3ds \
    Media/Models/Circuit/vallasPlastico_30.3ds \
    Media/Models/Circuit/vallasPlastico_29.3ds \
    Media/Models/Circuit/vallasPlastico_28.3ds \
    Media/Models/Circuit/vallasPlastico_27.3ds \
    Media/Models/Circuit/vallasPlastico_26.3ds \
    Media/Models/Circuit/vallasPlastico_25.3ds \
    Media/Models/Circuit/vallasPlastico_24.3ds \
    Media/Models/Circuit/vallasPlastico_23.3ds \
    Media/Models/Circuit/vallasPlastico_22.3ds \
    Media/Models/Circuit/vallasPlastico_21.3ds \
    Media/Models/Circuit/vallasPlastico_20.3ds \
    Media/Models/Circuit/vallasPlastico_19.3ds \
    Media/Models/Circuit/vallasPlastico_18.3ds \
    Media/Models/Circuit/vallasPlastico_17.3ds \
    Media/Models/Circuit/vallasPlastico_16.3ds \
    Media/Models/Circuit/vallasPlastico_15.3ds \
    Media/Models/Circuit/vallasPlastico_14.3ds \
    Media/Models/Circuit/vallasPlastico_13.3ds \
    Media/Models/Circuit/vallasPlastico_12.3ds \
    Media/Models/Circuit/vallasPlastico_11.3ds \
    Media/Models/Circuit/vallasPlastico_10.3ds \
    Media/Models/Circuit/vallasPlastico_9.3ds \
    Media/Models/Circuit/vallasPlastico_8.3ds \
    Media/Models/Circuit/vallasPlastico_7.3ds \
    Media/Models/Circuit/vallasPlastico_6.3ds \
    Media/Models/Circuit/vallasPlastico_5.3ds \
    Media/Models/Circuit/vallasPlastico_4.3ds \
    Media/Models/Circuit/vallasPlastico_3.3ds \
    Media/Models/Circuit/vallasPlastico_2.3ds \
    Media/Models/Circuit/vallasPlastico_1.3ds \
    Media/Models/Circuit/sky.3ds \
    Media/Models/Circuit/cat_sky_sun_01.dds

LIBS += -lgomp

QMAKE_CXXFLAGS+= -fopenmp
QMAKE_LFLAGS +=  -fopenmp

QMAKE_CFLAGS_RELEASE += -fopenmp
QMAKE_CFLAGS_DEBUG += -fopenmp


unix: CONFIG += link_pkgconfig
unix: PKGCONFIG += assimp

unix: CONFIG += link_pkgconfig
unix: PKGCONFIG += IL
